[build]
  command = "npm run build && node netlify/inject-env.js"
  publish = "out"

# Allow client-side routing to work by redirecting everything to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle specific Next.js asset routes
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 