[build]
  command = "npm run build && node netlify/inject-env.js"
  publish = "out"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/_404.html"
  status = 404

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 