-- Create table for practice sessions
CREATE TABLE IF NOT EXISTS practice_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  question TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  notes TEXT DEFAULT '',
  video_url TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Add row level security
ALTER TABLE practice_sessions ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own sessions
CREATE POLICY "Users can view their own practice sessions"
  ON practice_sessions
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Allow users to insert their own sessions
CREATE POLICY "Users can insert their own practice sessions"
  ON practice_sessions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Allow users to update their own sessions
CREATE POLICY "Users can update their own practice sessions"
  ON practice_sessions
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id);

-- Allow users to delete their own sessions
CREATE POLICY "Users can delete their own practice sessions"
  ON practice_sessions
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_practice_sessions_user_id 
  ON practice_sessions (user_id);

-- Comment on table and columns for better documentation
COMMENT ON TABLE practice_sessions IS 'Stores interview practice session recordings and feedback';
COMMENT ON COLUMN practice_sessions.id IS 'Unique identifier for the practice session';
COMMENT ON COLUMN practice_sessions.created_at IS 'Timestamp when the practice session was created';
COMMENT ON COLUMN practice_sessions.question IS 'The interview question that was answered';
COMMENT ON COLUMN practice_sessions.rating IS 'Self-rating of the answer quality (1-5)';
COMMENT ON COLUMN practice_sessions.notes IS 'User notes about their performance';
COMMENT ON COLUMN practice_sessions.video_url IS 'URL to the recorded video in Supabase storage';
COMMENT ON COLUMN practice_sessions.user_id IS 'Foreign key to the user who created this session'; 